# Generated by Django 3.2.3 on 2021-06-09 13:32

from django.db import migrations, models
import sales_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0008_auto_20210609_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=sales_manager.models.upload_to),
        ),
    ]
